import Head from 'next/head';
import Link from "next/link";
//import Image from 'next/image'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTwitter, faInstagram, faMixcloud, faDiscord, faSoundcloud, faTwitch } from "@fortawesome/free-brands-svg-icons";
//import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

//const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    /*
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>*/
    <>
      <Head>
        <title>
          loser4dim
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Resources/favicon.ico" />
        <link rel="apple-touch-icon" href="/Resources/logo192.png" />
      </Head>
      <main className={styles.App}>
        <noscript>
          You Need to Enable JavaScript to Run This Application.
        </noscript>
        <div className={styles.AppHeader}>
          <img src="/Resources/logo.png" className={styles.AppLogo} alt="logo" />
          <nav>
              <ul className={styles.AppLink}>
                
                <li>
                  <a href="https://www.mixcloud.com/loser4dim/">
                    <FontAwesomeIcon icon={faMixcloud} />
                  </a>
                </li>

                <li>
                  <a href="https://soundcloud.com/loser4dim">
                    <FontAwesomeIcon icon={faSoundcloud} />
                  </a>
                </li>
                <li>
                  <a href="https://instagram.com/loser4dim/">
                    <FontAwesomeIcon icon={faInstagram} />
                  </a>
                </li>

                <li>
                  <a href="https://discord.gg/3mPudy837n">
                    <FontAwesomeIcon icon={faDiscord} />
                  </a>
                </li>
                <li>
                  <a href="https://www.twitch.tv/loser4dim">
                    <FontAwesomeIcon icon={faTwitch} />
                  </a>
                </li>
                
                <li>
                  <a href="https://x.com/loser4dim/">
                    <FontAwesomeIcon icon={faTwitter} />
                  </a>
                </li>
              </ul>
              <ul className={styles.AppLink}>
                <li>
                  <a href="https://misskey.niri.la/@loser4dim/">
                    Misskey.niri.la
                  </a>
                </li>
                <li>
                  <a href="https://www.threads.net/@loser4dim/">
                    Threads
                  </a>
                </li>
                <li>
                  <Link href="/renderer4d">
                    Renderer4D-Developing
                  </Link>
                </li>
              </ul>
          </nav>
        </div>
      </main>
    </>
  );
}
